void FP_Open();
void FP_LED_open();
void FP_LED_close();
void FP_GetEnrollCount();
void FP_EnrollStart(int specify_ID);
void FP_Enroll(int Enroll_define);
void FP_IsPressFinger();
void FP_DeleteAll();
void FP_Identify();
void FP_CaptureFinger(unsigned long picture_quality);
void FP_GetTemplate();
void FP_SetTemplate();
void FP_GetDatabase();
void FP_SetDatabase();
void FP_DeviceSerialNumber();